"""Add inventory fields to books

Revision ID: e7fa81db9d0e
Revises: 8c99f769ca98
Create Date: 2025-12-04 11:33:32.022812

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e7fa81db9d0e'
down_revision: Union[str, Sequence[str], None] = '8c99f769ca98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "stock",
            sa.Integer(),
            nullable=False,
            server_default="1",  # default en la BD para registros existentes
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "language",
            sa.String(length=2),
            nullable=False,
            server_default="es",  # para que los libros existentes no queden en NULL
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "publisher",
            sa.String(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'language')
    op.drop_column('books', 'description')
    op.drop_column('books', 'stock')
    # ### end Alembic commands ###
