"""Add due_date, fine_amount and status to loans

Revision ID: a84de7dd6c28
Revises: 06bacdd4e5ab
Create Date: 2025-12-04 16:46:15.842701

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a84de7dd6c28'
down_revision: Union[str, Sequence[str], None] = '06bacdd4e5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    loan_status_enum = sa.Enum(
        "ACTIVE", "RETURNED", "OVERDUE", name="loan_status"
    )
    loan_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('loans', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('loans', sa.Column('status', loan_status_enum, server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')

    loan_status_enum = sa.Enum(
        "ACTIVE", "RETURNED", "OVERDUE", name="loan_status"
    )
    loan_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
